language: c
os: linux
sudo: false
compiler: gcc
dist: bionic

git:
  depth: 1

branches:
  except:
  - gh-pages

jobs:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - python3-pip 
        - python3-setuptools
        - python3-wheel 
        - ninja-build
env:
  global:
    - CODECOV_TOKEN=56604fc8-dafc-455a-aaca-2f12cc3f30d9

before_install:
  - pip3 install --user meson
  - pip3 install --user gcovr

script:
  - export PATH=~/.local/bin:/usr/local/gcc8/bin/:$PATH
  - export GCOV=gcov-8
  - env CC=gcc-8 meson build -Db_coverage=true
  - cd build
  - ninja
  - ninja test
  - ninja coverage-xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
