language: c
os: linux
sudo: false
compiler: gcc
dist: focal

git:
  depth: 1

branches:
  except:
  - gh-pages

jobs:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - python3-pip 
        - python3-setuptools
        - python3-wheel 
        - ninja-build
        - doxygen

before_install:
  - pip3 install --user meson
  - pip3 install --user gcovr

script:
  - export PATH=~/.local/bin:/usr/local/gcc8/bin/:$PATH
  - export GCOV=gcov-8
  - env CC=gcc-8 meson build_dbg -Db_coverage=true -Dbuildtype=debug
  - cd build_dbg
  - ninja
  - ninja test
  - ninja coverage-xml
  - cd ..
  - env CC=gcc-8 meson build
  - cd build
  - ninja
  - ninja test
  - ninja docs

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
