name: Continuous Integration

on:
  push:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  prepare:
    runs-on: windows-latest
    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1

  build_and_test:
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        compiler: [ clang, gcc ]
        type: [ Debug, Release ]
    steps:
      - name: Fetch ROOT-Sim repository
        uses: actions/checkout@v2
      - name: Install MPI
        uses: mpi4py/setup-mpi@v1
      - name: Build & Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.compiler }}
          build-type: ${{ matrix.type }}
          run-test: true
