name: Documentation Deployment

on:
  push:

jobs:
  update-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - name: Initialize Environment
        uses: ROOT-Sim/ci-actions/init@master
      - name: Generate Documentation
        uses: ROOT-Sim/ci-actions/docs@master
      - name: Documentation Coverage
        uses: ROOT-Sim/ci-actions/docs-coverage@master
        with:
          build-path: docs
      - name: Website Deployment
        uses: ROOT-Sim/ci-actions/website-deploy@master
